### ISSUE TITLE
problem with using ci-pug

### ISSUE THREAD

**Issue by anurat** [pug-php/ci-pug#2]
Hi @kylekatarnls ,

I use PHP 7 and Code Igniter 3.1.8
I followed the instruction on Readme, 
installed ci-pug via composer, the installation was successful,
set `$config['composer_autoload']` to `true`

On my controller I tried the following.
```
class Welcome extends CI_Controller {
	use Pug;

	public function pug() {
		$this->view( 'pug_template' );
	}
}
```
But I got an error `Welcome cannot use Pug\Pug - it is not a trait`

What else do I need to do?
Thanks in advance,

**Comment by kylekatarnls** [comment]
This error message is logical, indeed, `Pug` is not a trait and it's not how to use it, check the **How to use** section: https://github.com/pug-php/ci-pug#how-to-use-it
```php
<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Main extends CI_Controller {

  public function index()
  {
    $this->load->library('pug');
    $this->pug->view('myview');
  }
}
```
